- name: Logical Device Module
  hosts: localhost
  gather_facts: false
  vars_files:
    - ansible_vault_storage_var.yml
  vars:
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  tasks:
    - name: Create a Resource Group with virtual storage serial number of VSM
      hitachivantara.vspone_block.vsp.hv_resource_group:
        connection_info: "{{ connection_info }}"
        spec:
          name: "{{vsm_name}}"
          virtual_storage_serial: "{{virtual_serial}}"
          virtual_storage_model: "{{virtual_model}}"
      register: result