- name: Logical Device Module
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../ansible_vault_vars/ansible_vault_storage_var.yml
  vars:
    connection_info:
      address: "{{ storage_address }}"
      username: "{{ vault_storage_username }}"
      password: "{{ vault_storage_secret }}"
  tasks:
    - name: Swap-Split GAD pair
      hitachivantara.vspone_block.vsp.hv_gad:
        connection_info: "{{ secondary_connection_info }}"
        secondary_connection_info: "{{ connection_info }}"
        state: "swap_split"
        spec:
          copy_group_name: "{{copy_group_name}}"
          copy_pair_name: "{{copy_pair_name}}"
          local_device_group_name: "{{local_device_group_name}}"
          remote_device_group_name: "{{remote_device_group_name}}"
      register: result